### ISSUE TITLE
F-Droid

### ISSUE THREAD

**Issue by linsui** [lz233/unvcode_android#2]
请问可以将应用打包发布到 F-Droid 吗？

**Comment by lz233** [comment]
@linsui sure. just do yourself.

**Comment by linsui** [comment]
Thanks!

**Comment by linsui** [comment]
请问我可以在这个存储库里添加 fastlane 元数据吗？F-Droid 会从这里抓取应用描述。如果可以的话我开个 PR。

**Comment by lz233** [comment]
请便。

**Comment by linsui** [comment]
请问存储权限是做什么的？似乎没有用到。

**Comment by lz233** [comment]
年代久远，已经忘了（
如果确实没用的话，请 pr 将它移除

**Comment by linsui** [comment]
大概是没有用到，我没有授权它也没有请求。

**Comment by lz233** [comment]
那请 pr 移除，感谢

**Comment by linsui** [comment]
https://gitlab.com/fdroid/fdroiddata/-/merge_requests/11188 大概两三天后发布。谢谢！
